### PR TITLE
Update ex_menu.c

### PR DESCRIPTION
**Pull request by Sysmatix**
typo

### CODE REVIEW

**Comment by Sysmatix** [comment]
one more at line 129

**Comment by pedro-w** [comment]
The shortcut key for Exit on Windows traditionally always *was* X although googling doesn't show much evidence of that in newer apps. See for example:
image
(source: 
https://www.issco.unige.ch/en/research/tutoriel-informatique/EN/the_file_and_edit_menus.html)

**Comment by pedro-w** [comment]
@Sysmatix don't worry. In fact
*Welcome to Allegro!*
Hope you stick around and get into it! (check out [discord](https://discord.com/channels/993415281244393504/1013177108526276840) if you haven't already)

I had a bit of retro-enjoyment from this - it turns out ALT-F X is the key combo to quit Windows 2 (1987) so it's at least that old, maybe older?

**Comment by Sysmatix** [comment]
> @Sysmatix don't worry. In fact _Welcome to Allegro!_ Hope you stick around and get into it! (check out [discord](https://discord.com/channels/993415281244393504/1013177108526276840) if you haven't already)
> 
> I had a bit of retro-enjoyment from this - it turns out ALT-F X is the key combo to quit Windows 2 (1987) so it's at least that old, maybe older?

you gave me a link to a channel but i needed an invitation-link to the server..however i found it atanother allegro website and joined. prepare yourself for lots of beginner-questions :)

**Pull request closed without merging**
