### PR TITLE
fix osx catalina

### PR DESCRIPTION
**Pull request by allefant**

### CODE REVIEW

**Comment by allefant** [comment]
Unfortunately could not find any documentation on what the update() call is supposed to do exactly, but the skater demo works again with this on OSX Catalina, including window resizing.

**Comment by elias-pschernig** [comment]
Oh, and I forgot to mention, this also places the activateIgnoringOtherApps call on the main thread - which turned out to be just a harmless warning, but is still the right thing to do.

Anyway, issue #1091 seems to be fixed with this, unless we discover the original purpose of the update() call.

**Comment by elias-pschernig** [comment]
Well, after figuring out the difference in objective C between @selector(update) and @selector(update:) it now does call update again, from the main thread. Should be 100% identical to before now, just works in Catalina.

**Comment by djn658** [comment]
Thank you very much! It works now.

**Comment by mbkorecki** [comment]
Hi, thanks a lot for the fix. I wanted to check it out but I am having issues building allegro. I tried building with gcc/g++-9 and with clang as well as an xcode project. In each case I get errors (different depending on compilers). For clang I get an error stating that the problem is: "use of undeclared identifier 'errno'". It seems weird as the file that throws the error does include the errno.h. May I ask how you build allegro on your system? Perhaps someone experienced this error as well?

**Comment by mbkorecki** [comment]
Thanks a lot. It works for me as well.

**Comment by SiegeLord** [comment]
Thanks for all the testing everyone, and Elias for writing this!

**Pull request merged**
