### PR TITLE
make it work with clang 3.1

### PR DESCRIPTION
**Pull request by elias-pschernig**
Replaces #541 which was against the 5.1 branch.

### CODE REVIEW

**Comment by peterhull90** [comment]
I've been looking at which version of clang goes with which version of XCode. From this
https://en.wikipedia.org/wiki/Xcode
AFAICS Apple Clang 3.1 goes with XCode 4.3, Clang 4.0 goes with XCode 4.4 and the latter drops support for OS X Snow Leopard (2009). (However both 3.1 and 4.0 were based on LLVM 3.1).
But I'm not sure how these *compiler* changes affect the target *runtime* version - i.e. does this patch allow people with relatively old versions of XCode to continue compiling Allegro or does it affect the end user (people writing games with Allegro and people playing games written with Allegro)

All in all, I'm confused :confused:

**Comment by trentg** [comment]
Does this compile with newer clang as well? I'm not sure but I recall some of the lines you've changed were just changed recently... not sure if it matters but perhaps someone remembers what those changes were about and if these modifications don't undo them.

**Comment by peterhull90** [comment]
Yes I am confident it will work on newer versions. The changes are just
removing uses of the shortcut methods for object literals which were added
in more recent Clangs.

**Comment by elias-pschernig** [comment]
Basically @{ is a shortcut for creating an NSDictionary, @autoreleasepool is a shortcut for [NSAutoreleasePool] alloc/init/release, and "instancetype" is similar to C++ "auto" but you can still use "id" (which is similar to C++ "void *").

**Comment by SiegeLord** [comment]
Merged as 74855c8 for consistency. That said, my preference would be to drop support for older clang versions and modernize the code wholesale at some point.

**Pull request closed without merging**
