### PR TITLE
Don't stop and join the timer thread when stopping the last timer.

### PR DESCRIPTION
**Pull request by goobliata**
On Windows were al_rest is very inaccurate, al_stop_timer could
cause a long unwanted delay when joining the thread before this.

### CODE REVIEW

**Comment by SiegeLord** [comment]
We should probably add a condition variable inside that thread that waits until _al_vector_size goes above 0 so that we can suspend that thread entirely.

**Comment by goobliata** [comment]
I did that, just have to test it when I get back to my Windows machine.

**Comment by goobliata** [comment]
Didn't find any problems on Windows, Mac or Linux in my games.

**Comment by SiegeLord** [comment]
This looks great, I'm glad we could fix this without adding more API.

**Pull request merged**
