### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by Tamonash-glitch**

### CODE REVIEW

**Comment by beoran** [comment]
First of all, thanks for all your hard work. However, it is not very clear what you are trying to accomplish, could you please explain?

Secondly, the PR has a merge conflict and targets the 4.2 branch. That branch is obsolete now, I assume you wanted to target the 5.x branch?

**Comment by pedro-w** [comment]
@beoran another project I contribute to has received spammy pull requests like this and someone there said that it is related to the 'hacktoberfest' promotion, where Digital Ocean offer free t-shirts to people contributing to open source. So I would ignore this for now and see if Tamonash-glitch gets back with anything more sensible.

**Comment by beoran** [comment]
I hope that is not the case, but if this PR is just spam, then we will lock it. I suggest we leave the OP one week to respond.

**Comment by pedro-w** [comment]
If it is due to hacktoberfest, DigitalOcean's [FAQ](https://hacktoberfest.digitalocean.com/faq) says to label them 'invalid' and close. I can't do this myself, it would have to be SL or Elias I suppose.

**Comment by beoran** [comment]
Closing due to supspected Hacktober SPAM. OP, if this was intended a serious contribution, please clean it up and resubmit it. Thanks for your understanding.

**Comment by beoran** [comment]
@pedro-w I am not very active on Allegro5 as of lately, but I still keep track of it and I still have the commit bit. Thanks for the Hacktober tip.

**Pull request closed without merging**
