### PR TITLE
Fix to ex_camera: camera's axes are now properly normalized

### PR DESCRIPTION
**Pull request by 1Hyena**
This fixes a bug that used to freeze the camera when the user rotated it at a very rapid pace. Attached are screenshots of the bug.
ex_camera_1
ex_camera_2

### CODE REVIEW

**Comment by elias-pschernig** [comment]
Instead of normalizing the third vector, would it be better to set it as the cross product of the first two?

**Comment by 1Hyena** [comment]
@elias-pschernig you are right. By using cross product here it becomes trivial to also maintain perpendicularity of the axes. I have made the respective changes to this branch.

**Comment by 1Hyena** [comment]
@elias-pschernig 
Actually this can be optimized even more like this:

```
al_transform_coordinates_3d(&t, &c->zaxis.x, &c->zaxis.y, &c->zaxis.z);
al_transform_coordinates_3d(&t, &c->yaxis.x, &c->yaxis.y, &c->yaxis.z);

c->zaxis = vector_normalize(c->zaxis);
c->xaxis = vector_cross_product(c->yaxis, c->zaxis);
c->xaxis = vector_normalize(c->xaxis);
c->yaxis = vector_cross_product(c->zaxis, c->xaxis);
```

Unfortunately I can test this code and make a new commit on Monday the earliest. I'd suggest waiting until then before merging.

**Comment by 1Hyena** [comment]
I also made the skybox move with the camera's y-position because in airplane or spaceship mode it was possible to fly through the skybox. @elias-pschernig let me know if there is anything else you think needs modification here before merging.

**Comment by elias-pschernig** [comment]
I always found it funny that I could reach the top of the skybox, but I agree that for the sake of being an example it should be a real skybox where this is not possible. Applied it all, thanks!

**Pull request merged**
