### PR TITLE
Replaced the custom _al_set_error method 

### PR DESCRIPTION
**Pull request by tbass**
with the default ALLEGRO_ERROR call as it does not do anything else

Removed all traces of the _al_set_error functionality

refers to issue #194

### CODE REVIEW

**Comment by goobliata** [comment]
This could be used at some point to add error codes, so I will not accept this. Also the error codes are not shown anymore which might be helpfull.

**Comment by SiegeLord** [comment]
I think the intended way to solve that was perhaps to do:

```
al_set_errno(ALLEGRO_GENERIC_ERROR);
ALLEGRO_ERROR("A driver already running");
```

Granted, `al_set_errno` isn't often used anyway. Alternatively maybe the right way would be to move that custom _al_set_error into the main library and rename it?

**Comment by SiegeLord** [comment]
In terms of the first suggestion it could be as simple as sticking the `al_set_errno` inside `_al_set_errno`, hah.

**Comment by goobliata** [comment]
yes it would make sense to use al_set_errno, just make sure the codes don't collide with existing ones.

**Pull request closed without merging**
