### PR TITLE
Fix failing FLAC compile test not being able to run again

### LINKED ISSUE #533: FLAC compile test fails
Have I ever mentioned that I hate CMake? :rage:

All required dependencies (including FLAC.lib) are in `deps/`, CMake finds them successfully and they are listed next to the relevant variables, e.g. `FLAC_LIBRARY`.  However, the compile test fails with the following output:

```
Performing C SOURCE FILE Test FLAC_COMPILES failed with the following output:
Change Dir: D:/src/allegro5/build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_5dad0.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.23107.0

Copyright (C) Microsoft Corporation. All rights reserved.



Build started 12/6/2015 10:03:26 PM.

Project "D:\src\allegro5\build\CMakeFiles\CMakeTmp\cmTC_5dad0.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_5dad0.dir\Debug\".

  Creating directory "D:\src\allegro5\build\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_5dad0.dir\Debug\cmTC_5dad0.tlog\".

InitializeBuildStatus:

  Creating "cmTC_5dad0.dir\Debug\cmTC_5dad0.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /ID:\src\allegro5\deps\include /Zi /W4 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D FLAC_COMPILES /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_5dad0.dir\Debug\\" /Fd"cmTC_5dad0.dir\Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue D:\src\allegro5\build\CMakeFiles\CMakeTmp\src.c

  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23026 for x86

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /ID:\src\allegro5\deps\include /Zi /W4 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D FLAC_COMPILES /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_5dad0.dir\Debug\\" /Fd"cmTC_5dad0.dir\Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue D:\src\allegro5\build\CMakeFiles\CMakeTmp\src.c

  

  src.c

Link:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"D:\src\allegro5\build\CMakeFiles\CMakeTmp\Debug\cmTC_5dad0.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib D:\src\allegro5\deps\lib\FLAC.lib D:\src\allegro5\deps\lib\ogg.lib wsock32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /Debug /PDB:"D:/src/allegro5/build/CMakeFiles/CMakeTmp/Debug/cmTC_5dad0.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/src/allegro5/build/CMakeFiles/CMakeTmp/Debug/cmTC_5dad0.lib" /MACHINE:X86 /SAFESEH  /machine:X86 /debug cmTC_5dad0.dir\Debug\src.obj

src.obj : error LNK2019: unresolved external symbol __imp__FLAC__stream_decoder_new referenced in function _main [D:\src\allegro5\build\CMakeFiles\CMakeTmp\cmTC_5dad0.vcxproj]

D:\src\allegro5\build\CMakeFiles\CMakeTmp\Debug\cmTC_5dad0.exe : fatal error LNK1120: 1 unresolved externals [D:\src\allegro5\build\CMakeFiles\CMakeTmp\cmTC_5dad0.vcxproj]

Done Building Project "D:\src\allegro5\build\CMakeFiles\CMakeTmp\cmTC_5dad0.vcxproj" (default targets) -- FAILED.



Build FAILED.



"D:\src\allegro5\build\CMakeFiles\CMakeTmp\cmTC_5dad0.vcxproj" (default target) (1) ->

(Link target) -> 

  src.obj : error LNK2019: unresolved external symbol __imp__FLAC__stream_decoder_new referenced in function _main [D:\src\allegro5\build\CMakeFiles\CMakeTmp\cmTC_5dad0.vcxproj]

  D:\src\allegro5\build\CMakeFiles\CMakeTmp\Debug\cmTC_5dad0.exe : fatal error LNK1120: 1 unresolved externals [D:\src\allegro5\build\CMakeFiles\CMakeTmp\cmTC_5dad0.vcxproj]



    0 Warning(s)

    2 Error(s)



Time Elapsed 00:00:00.75


Source file was:

            #include <FLAC/stream_decoder.h>
            int main(void)
            {
                (void)FLAC__stream_decoder_new();
                return 0;
            }
```

This prevents me from building Allegro with FLAC support.  The libs are from the official package at http://download.gna.org/allegro/allegro-deps/1.2.0/

### PR DESCRIPTION
**Pull request by fatcerberus**
Fixes #533.

It turns out that the variable provided to `check_c_source_compiles` is a cache variable, which means if the compile test fails the failure result is saved and CMake avoids running the check again.  The solution is just to unset `FLAC_COMPILES` after a failed test, so that it will run again on the next configure.

### CODE REVIEW

**Comment by fatcerberus** [comment]
What I find interesting is why the compile test fails at all when `FLAC_STATIC` isn't set properly.  As long as the symbols are present, the linker shouldn't care whether they come from the library or a DLL?

**Comment by elias-pschernig** [comment]
Can we get CMake to do this for *all* failed tests? Re-run them the next time that is. It caused me hours and hours of frustration over the years that it would simply ignore new libraries just because they were not found at some point in the past...

**Comment by fatcerberus** [comment]
Sure, I could make that change easy enough.  I was thinking of doing that actually, it's just FLAC has caused me the most grief.

**Comment by SiegeLord** [comment]
If we're going to do it for everything, there should probably be a function in `common.cmake` to wrap this logic, perhaps.

**Comment by fatcerberus** [comment]
I don't know if that's possible -- is it possible to have a "computed" variable name?  The fix works by deleting the check variable upon failure.

**Comment by SiegeLord** [comment]
Yeah, it is. See, e.g. `append_lib_type_suffix` and others in `Common.cmake`.

**Comment by fatcerberus** [comment]
Okay, all the compile tests now use the new logic.  And my brain is numb from dealing with CMake's fugly scripting language...

**Comment by fatcerberus** [comment]
Alright, this should be ready to be merged unless there are any issues.  No problems have come up in my own testing, at least.

Note that a *successful* compile test will never be re-run regardless of changed settings (short of deleting the CMakeCache anyway), but that's just a consequence of how the cache works and shouldn't be too big an issue in practice.  The important thing is that failed tests get another chance to run if the first configure doesn't get everything right (which seems quite common).

**Comment by SiegeLord** [comment]
Could you rebase this over the most recent 5.1? I've fixed the AppVeyor scripts so it'd be nice to give this one last round of tests.

**Comment by fatcerberus** [comment]
No problem, done.

**Comment by SiegeLord** [comment]
Thanks!

**Pull request merged**
