### PR TITLE
allegro5.cfg: fix incorrect config file name referenced in the comments

### PR DESCRIPTION
**Pull request by dos1**
I've got burned by this once or twice already :P

### CODE REVIEW

**Comment by elias-pschernig** [comment]
Ha! How did you find that out? Anyway, problem with your "fix" is that the documentation is actually correct, but there is a typo in the code. I.e. the file was named ~/.allegrorc in Allegro 4 and was meant to keep the leading dot with Allegro 5: ~/.allegro5rc (just like for example ~/.bashrc or ~/.vimrc or any ancient unix programs).

**Comment by SiegeLord** [comment]
Let's just support both, since maybe there's some person relying on this.

**Comment by dos1** [comment]
Haha. I found it out by wondering why my .allegro5rc file wasn't taken into effect. I've checked and turned out both documentation and the code says "allegro5rc" while the comments in the config file itself say ".allegro5rc". Yes, the version with dot is what I'd expect, I'll modify this PR :)

**Comment by dos1** [comment]
Updated!

**Comment by SiegeLord** [comment]
Merged as dd285c8d089e35ea2a94ca0e295c9806880e6901, thanks!

**Pull request closed without merging**
