### PR TITLE
Only test cooperative lavel if device is known to be lost.

### PR DESCRIPTION
**Pull request by SiegeLord**
@goobliata We reverted a version of this patch a few years ago as it broke some of your games. Could you test this one on them?

### CODE REVIEW

**Comment by goobliata** [comment]
One of my games crashes on reset with this, I'll have to investigate it.

**Comment by SiegeLord** [comment]
Perfect, let me know if I can be of help.

**Comment by goobliata** [comment]
I can reproduce the crash in ex_fs_window by adding ALLEGRO_PROGRAMMABLE_PIPELINE to the flags (at first I was trying to fix my game but after being unable to fix it, I tried to reproduce it in the example because it's also crashing in toggling fullscreen window in my game.)

**Comment by goobliata** [comment]
Possible hint: it was crashing in al_draw_prim in my game, ex_fs_window also draws primitives, perhaps it's the primitive shaders.

**Comment by goobliata** [comment]
I haven't looked into the cause of the crash yet. It might just be that we're not releasing everything when we toggle fullscreen window.

**Comment by SiegeLord** [comment]
I got it crashing with ex_fs_window too, like you said; haven't had time to look at it.

**Comment by SiegeLord** [comment]
Turns out we were leaking D3D shaders if we attached both pixel and vertex shader sources. The commit here fixes the crash with ex_fs_window. Could you test this again? Thanks!

**Comment by goobliata** [comment]
Works in my game now as well.

**Pull request merged**
