### PR TITLE
Python 3 bindings #691

### PR DESCRIPTION
**Pull request by gjvnq**
Solves issue #691 by making the code compatible with both python2 and python3.

### CODE REVIEW

**Comment by elias-pschernig** [comment]
What happens if someone has no Python installed? And what is the minimum version of Python 2 that is required now?

**Comment by gjvnq** [comment]
I've used Python 2.7.12 and Python 3.5.2 for testing. So, I imagine that Python 2.7 is the minimum version.

However, I simply forgot the possibility of no python being available. The simplest fix is to keep the line 150 of the file CMakeLists.txt as it is (i.e. not building python bindings by default)

The best solution, in my opinion, would be to automatically install the python bindings only if python is available and simply ignore/not build the bindings if it python is not available.

**Comment by beoran** [comment]
I would prefer if the Python bindings stay not built by default as they are
now. Even though Python is installed on my system, I have no use for the
bindings. So I don't want to have wait for them to compile.

Kind Regards, B.

On 27 Nov 2016 10:37 pm, "Gabriel Queiroz" <notifications@github.com> wrote:

I've used Python 2.7.12 and Python 3.5.2 for testing. So, I imagine that
Python 2.7 is the minimum version.

However, I simply forgot the possibility of no python being available. The
simplest fix is to keep the line 150 of the file CMakeLists.txt as it is
(i.e. not building python bindings by default)

The best solution, in my opinion, would be to automatically install the
python bindings only if python is available and simply ignore/not build the
bindings if it python is not available.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/liballeg/allegro5/pull/694#issuecomment-263149392>, or mute
the thread

**Comment by gjvnq** [comment]
@eoran, I reverted `WANT_PYTHON_WRAPPER` to the previous state (i.e. `off`).

**Comment by beoran** [comment]
Thanks. I will leave it to someone else to merge this, though...

**Comment by SiegeLord** [comment]
Thanks!

**Pull request merged**
