### PR TITLE
Use unique ids to identify menu items internally.

### LINKED ISSUE #816: Reusing ids with different menus leads to confusion with respect to event sources.
This is due to Allegro using the id to do the reverse lookup to the menu item that generated the event.

Two action points here:

- [ ] document the status quo better
- [ ] try to fix it. On every platform except Windows we have complete control over the id type.

### PR DESCRIPTION
**Pull request by SiegeLord**
Fixes #816.

### CODE REVIEW

**Comment by oitofelix** [comment]
Do you think this change might somehow break code relying on the previous non-unique behavior, or is it safe as a drop-in replacement?  I have a huge menu module for my game on which I've spent quite some time and I don't want to revisit it for now.

Ps: By the way, thank you for working on improving Allegro's menu interface!

**Comment by fatcerberus** [comment]
@oitofelix I suspect most people would consider the previous behavior a bug, like you did.

**Comment by SiegeLord** [comment]
This patch has two effects, making the `al_enable_menu_event_source` work for multiple menus, and also making the events' menu pointer point correctly to the new menu. The only way I can imagine this breaking code is if people somehow depended on that menu pointer not changing. It seems unlikely enough to me. I figure most people just compare the returned ids and not realize something's funky is going on under the hood.

**Comment by SiegeLord** [comment]
Tested it on OSX, Windows and Linux... everything seems to work fine. Merging!

**Pull request merged**
