### PR TITLE
fix some android crashes

### PR DESCRIPTION
**Pull request by elias-pschernig**
This change seems to fix quite a few crashes I got on various Android
devices on Amazon AWS device farm (unfortunately my 250 free minutes are
used up so can't do any more testing).

### CODE REVIEW

**Comment by elias-pschernig** [comment]
Just putting this up here, it's certainly not a clean fix as I can't even figure out how it can happen - the surface gets set to null when it is destroyed... but some race condition makes Allegro try and create it a second time. By simply ignoring the second time (it seems to always happen within the first second of starting the game) my game works instead of crashing. So if nobody sees an obvious problem with it I'd like to apply anyway, it does make Allegro work on more Android devices after all - and hopefully at some point someone will clean up the surface/display handling on the Android port and actually fix the issue. I can't follow the jungle of all the undocumented d->first_run, d->created, d->recreated, d->is_destroy_display... fields in ANDROID_DISPLAY at all :P

**Comment by SiegeLord** [comment]
Maybe there should be a comment along the lines of what you said above, so the future person knows that this isn't a proper fix :smile:.

**Comment by elias-pschernig** [comment]
Indeed, I added a comment.

**Comment by elias-pschernig** [comment]
Fixed this with commit c3493b instead I believe.

**Pull request closed without merging**
