### PR TITLE
Work around crashes on some Androids when an FBO is bound during egl_…

### PR DESCRIPTION
**Pull request by goobliata**
…SwapBuffers

### CODE REVIEW

**Comment by goobliata** [comment]
For future note the device is a 1st gen Kindle Fire with Android 2.3.

**Comment by elias-pschernig** [comment]
I don't understand what this does... does al_set_target_bitmap clear FBO bindings? If that's the case, could clearing FBOs have any possible side effects?

**Comment by goobliata** [comment]
FBO is bound when you set the target to a bitmap. So on some devices if the target is a bitmap (and not the display), it will crash on flip. This has no side effects because it's set back right after the flip.

**Comment by elias-pschernig** [comment]
Sounds good to me then!

**Comment by goobliata** [comment]
Just Yet Another Stupid Workaround for Android! :)

**Pull request merged**
