### PR TITLE
make enumerating connected joysticks more robust

### PR DESCRIPTION
**Pull request by peterhull90**
Developed by @NewCreature. As discussed on [a.cc](https://www.allegro.cc/forums/thread/616193/1021898#target)

### CODE REVIEW

**Comment by SiegeLord** [comment]
Finally got around to looking at this, sorry for the delay.

One issue I found is that it somehow detects 1 extra button than the old code for my Logitech F310 controller. It detects 13 buttons, while the old code only detects 12 (and try as I might, I don't see where the 13th button is). I looked at the code, but it's not obvious to me where the issue is (or if it's a bug in the OSX itself).

**Comment by NewCreature** [comment]
Do the analog sticks click down as buttons? My Wii U Pro controllers had 2 extra buttons I couldn't locate, but it turns out it was those.

**Comment by SiegeLord** [comment]
Yeah, it detected the analog stick buttons fine.

I managed to find the 13th button, but I don't seem to get events from it (I do get events from it on Linux). The input callback doesn't even get called for it, so it's not like we're filtering it out somehow.

**Comment by fatcerberus** [comment]
I used to have an F310 myself, I remember a lot of software (including Windows control panel) used to detect a seemingly phantom button on it.  It's the Analog button, isn't it?

**Comment by SiegeLord** [comment]
It's the button between back and start buttons in the middle. The one with the logitech logo.

**Comment by NewCreature** [comment]
Maybe try it with [Enjoyable](https://yukkurigames.com/enjoyable/) to see if it detects the 13th button and allows it to map to something.

**Comment by SiegeLord** [comment]
Merged as 0828211. Thanks to you both!

I decided not to worry about the 13th button, this patch is still a strict improvement over the current situation.

**Pull request closed without merging**
