### PR TITLE
Generate LuaJIT API for Allegro 5

### PR DESCRIPTION
**Pull request by billyquith**
This Python script generates a Lua file containing a C declaration of Allegro 5 API suitable for use by LuaJIT.

### CODE REVIEW

**Comment by billyquith** [comment]
Whoops. Should have branched. Seems to have incorporated other changes for some reason.

**Comment by SiegeLord** [comment]
Could you rebase on top of master? It should remove all these extra commits.

Also, could you move this to a contrib directory (so it looks like `contrib/luajit') and maybe add a small readme to it? Lastly, it should be relatively simple for you to just copy the CMakeLists.txt from the python directory and make Allegro generate these things semi-automatically. That's optional though if you think it's too difficult.

**Comment by LukeMS** [comment]
I've just downloaded billyquith's script, generated the prototype and the FFI wrapper, used it, and everything works flawlessly (at least as far as installing the system and creating the display goes).  :+1: 
Also I've created a small sample repo showing how to use the luajit FFI for allegro5 [here](https://github.com/LukeMS/allegro5_luajit_ffi).
Is this going to be merge into the master branche?
Only thing neeeded is to create the contrib folder?

**Comment by billyquith** [comment]
Oops, sorry, forgot about this (changed job, moved house, ya know...). As @SiegeLord points out I cocked up the git workflow, so it needs a rebase. 

cmake isn't so hard, especially if you understand autoconfig etc! 😃

**Comment by LukeMS** [comment]
Just noticed that ALLEGRO_VERSION_INT requires a hack:

`    f.write('-- CONSTANTS\n')
    deferred = []
    deferred_dict = {}
    for name, val in sorted(al.constants.items()):
        deferred_dict[name] = val
        try:
            if isinstance(val, str):
                val = int(eval(val, globals(), al.constants))
            f.write('allegro.%s = %s\n' % (name, str(val)))
        except:
            deferred.append((name, val))

    allegro_version_int = (
        deferred_dict["ALLEGRO_VERSION"] << 24 |
        deferred_dict["ALLEGRO_SUB_VERSION"] << 16 |
        deferred_dict["ALLEGRO_WIP_VERSION"] << 8 |
        deferred_dict["ALLEGRO_RELEASE_NUMBER"]
    )
    f.write('allegro.%s = %s\n' % ("ALLEGRO_VERSION_INT",
                                   str(allegro_version_int)))

    reconst = re.compile('([A-Za-z_]\w+)')
    for name, val in deferred:
        val = reconst.sub(r'allegro.\1', val)
        f.write('allegro.%s = %s\n' % (name, str(val)))`

**Comment by billyquith** [comment]
I made the other changes you suggested.

I tried rebasing this (a technique I'm not overly familiar with) and it doesnt seem to have worked. It may be better to apply a patch.

**Comment by SiegeLord** [comment]
Wow, this was really messed up gitting there, hah! Still, I figured it out and it is now merged (with some of my fixes) here https://github.com/liballeg/allegro5/commit/eaa77d05dfa70e249b29f77dee0d8f181c9ee3ff.

@billyquith If possible, would you be able to add a very simple lua file illustrating how to use it? I unfortunately don't know LUA at all.

**Comment by billyquith** [comment]
Sorry about that! I've no idea what I did, it certainly didn't turn out as expected!

Yep, can add an example. I'll try and use git workflow this time!

BTW, it is Lua (not an acronym). It means moon in Portuguese.

Merry Xmas! 🎁 🎄 🎅

**Pull request closed without merging**
